<a href="https://colab.research.google.com/github/ChrxsCrxss/DS4A-Capstone/blob/main/Group.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_excel(r'/content/PopulationEstimates (1).xls')
df.head(10)

  Population estimates for the U.S., States, and counties, 2010-19 (see the second tab in this workbook for variable name descriptions)  ...    Unnamed: 164
0  These data were posted to the ERS website (at ...                                                                                     ...             NaN
1                                            FIPStxt                                                                                     ...  R_NET_MIG_2019
2                                              00000                                                                                     ...             NaN
3                                              01000                                                                                     ...         2.48374
4                                              01001                                                                                     ...         4.56006
5                                              01003                                                                                     ...         24.3806
6                                              01005                                                                                     ...        -5.16566
7                                              01007                                                                                     ...         1.83195
8                                              01009                                                                                     ...          1.1246
9                                              01011                                                                                     ...        -7.20099

[10 rows x 165 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')